manifest_version = "1"
id = "kinesis-rust"
description = "Kinesis handler/trigger using Rust."
tags = ["kinesis", "rust"]

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
kinesis-arn = { type = "string", prompt = "Kinesis ARN", default = "" }
batch-size = { type = "number", prompt = "Kinesis Batch Size", default = "10" }
shard-idle-wait-millis
detector-poll-millis
shard-iterator-type
component = 