spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.kinesis]]
stream_arn = "{{stream-arn}}"
batch_size = "{{batch-size}}"
shard_idle_wait_millis = "{{shard-idle-wait-millis}}"
detector_poll_millis = "{{detector-poll-millis}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "target/wasm32-wasi/release/{{project-name | snake_case}}.wasm"
[component.{{project-name | kebab_case}}.build]
command = "cargo build --target wasm32-wasi --release"